### ISSUE TITLE
How to listen for Webview close with Ideal redirect  component

### ISSUE THREAD

**Issue by ranjith-thandayuthapani** [Adyen/adyen-android#777] opened 2022-09-06 12:12 UTC
I am using Ideal and Redirect component for iDeal Pay. After the webview is launched, if user close the webview i need to perform certain action. now redirect component's observeErrors is not triggered. Where we can listen for the webview close.

**Comment by albinus-sc** [comment] 2022-09-12 11:24
I think this might be the same issue as https://github.com/Adyen/adyen-android/issues/582

**Comment by jreij** [comment] 2022-09-13 08:33
Hi, thanks for reaching out. Yes indeed this is a duplicate of #582, please check the discussion there for a detailed explanation.

**Closed by jreij** 2022-09-13 08:33 UTC
Labels: duplicate
