### ISSUE TITLE
Keyboard Obscures Pay Button on Card Payment Screen in Drop-in v5.3.1

### ISSUE THREAD

**Issue by timatpam** [Adyen/adyen-android#1617] opened 2024-05-03 14:06 UTC
Observed Behavior: In version 5.3.1 of the Drop-in payment interface, when a user opts to make a payment with a card and begins entering their card information, the on-screen keyboard appears as expected. However, after the card details are entered, the 'Pay' button is not visible because it is covered by the keyboard. Additionally, the card detail view is not scrollable, and the 'Pay' button cannot be reached using the 'Next' (Enter) button on the keyboard. The user is unable to scroll to reveal the 'Pay' button; the only workaround is to manually dismiss the keyboard.

Expected Behavior: The behavior should be consistent with that of version 4.x, where the card detail screen allows for scrolling to the 'Pay' button. After filling in the card details, pressing the 'Next' (Enter) button on the keyboard should allow the user to proceed to the 'Pay' button, ensuring a smooth and uninterrupted payment process.

**Comment by jreij** [comment] 2024-05-06 10:07
Hi @timatpam , can you check whether the [suggested fix in this other issue](https://github.com/Adyen/adyen-android/issues/1562#issuecomment-2072141847) solves your problem as well? If not, could you please provide a screen recording of this issue to help us investigate and reproduce?

**Comment by timatpam** [comment] 2024-05-08 01:21
Hi @jreij , this fixed scroll.
But unfortunately 'Pay' button still cannot be reached using the 'Next' (Enter) button on the keyboard, the card icon is activated and clicked instead.

**Comment by jreij** [comment] 2024-05-08 10:56
@timatpam good to hear the scrolling issue was fixed.

As for the button, I could not reproduce this yet, can you provide some additional information to help me investigate:
- With which emulator or device are you facing this issue? Have you tried on multiple devices as well?
- Can you share a screen recording of the issue?

One thing you can try is to test your app with the default SDK theme by adding `<style name="AdyenCheckout" parent="Adyen"/>` to your `styles.xml` file and removing any other instances of `AdyenCheckout`. If this works then I assume there is something to be fixed in your theming.  Let me know what you can find.

**Comment by timatpam** [comment] 2024-05-14 07:41
There is no issue with `<style name="AdyenCheckout" parent="Adyen"/>` in `styles.xml` so it seems to be our Adyen style customization issue.

**Comment by jreij** [comment] 2024-06-10 08:22
Hi @timatpam, did you manage to resolve your problem? Feel free to reopen this issue if you still need help with it

**Closed by jreij** 2024-06-10 08:22 UTC
Labels: Bug report
