### ISSUE TITLE
Memory Leak /w Adyen Integration 

### ISSUE THREAD

**Issue by RikNorakomi** [Adyen/adyen-android#9] opened 2017-09-29 09:33 UTC
It seems like your sdk is causing a memory leak.
Here's the LeakCanary log:

* com.adyen.ui.activities.CheckoutActivity has leaked:
* GC ROOT static android.support.v4.content.LocalBroadcastManager.mInstance
* references android.support.v4.content.LocalBroadcastManager.mReceivers
* references java.util.HashMap.table
* references array java.util.HashMap$HashMapEntry[].[4]
* references java.util.HashMap$HashMapEntry.key
* references com.adyen.ui.activities.CheckoutActivity$1.this$0 (anonymous subclass of android.content.BroadcastReceiver)
* leaks com.adyen.ui.activities.CheckoutActivity instance

* Retaining: 109KB.
* Reference Key: 00b860ae-83bf-45f9-bdce-db571d0c5b51
* Device: HUAWEI HUAWEI HUAWEI TAG-L21 TAG-L21
* Android Version: 5.1 API: 22 LeakCanary: 1.5.1 1be44b3
* Durations: watch=5191ms, gc=173ms, heap dump=2081ms, analysis=39879ms

* Details:
* Class android.support.v4.content.LocalBroadcastManager
|   static DEBUG = false
|   static $staticOverhead = byte[40]@583208001 (0x22c30c41)
|   static MSG_EXEC_PENDING_BROADCASTS = 1
|   static mLock = java.lang.Object@590233024 (0x232e3dc0)
|   static mInstance = android.support.v4.content.LocalBroadcastManager@590245088 (0x232e6ce0)
|   static TAG = java.lang.String@583126624 (0x22c1ce60)
* Instance of android.support.v4.content.LocalBroadcastManager
|   static DEBUG = false
|   static $staticOverhead = byte[40]@583208001 (0x22c30c41)
|   static MSG_EXEC_PENDING_BROADCASTS = 1
|   static mLock = java.lang.Object@590233024 (0x232e3dc0)
|   static mInstance = android.support.v4.content.LocalBroadcastManager@590245088 (0x232e6ce0)
|   static TAG = java.lang.String@583126624 (0x22c1ce60)
|   mActions = java.util.HashMap@590228448 (0x232e2be0)
|   mAppContext = nl.beelen.business.BeelenApplication@584859488 (0x22dc3f60)
|   mHandler = android.support.v4.content.LocalBroadcastManager$1@590245120 (0x232e6d00)
|   mPendingBroadcasts = java.util.ArrayList@590245152 (0x232e6d20)
|   mReceivers = java.util.HashMap@590228496 (0x232e2c10)
* Instance of java.util.HashMap
|   static MINIMUM_CAPACITY = 4
|   static serialPersistentFields = java.io.ObjectStreamField[1]@1889097328 (0x70995670)
|   static EMPTY_TABLE = java.util.HashMap$HashMapEntry[2]@1889097672 (0x709957c8)
|   static serialVersionUID = 362498820763181265
|   static $staticOverhead = byte[48]@1889389041 (0x709dc9f1)
|   static MAXIMUM_CAPACITY = 1073741824
|   static DEFAULT_LOAD_FACTOR = 0.75
|   entryForNullKey = null
|   entrySet = null
|   keySet = null
|   modCount = 13
|   size = 1
|   table = java.util.HashMap$HashMapEntry[8]@590228544 (0x232e2c40)
|   threshold = 6
|   values = null
|   keySet = null
|   valuesCollection = null
* Array of java.util.HashMap$HashMapEntry[]
|   [0] = null
|   [1] = null
|   [2] = null
|   [3] = null
|   [4] = java.util.HashMap$HashMapEntry@590245248 (0x232e6d80)
|   [5] = null
|   [6] = null
|   [7] = null
* Instance of java.util.HashMap$HashMapEntry
|   hash = -1530459604
|   key = com.adyen.ui.activities.CheckoutActivity$1@589182336 (0x231e3580)
|   next = null
|   value = java.util.ArrayList@590391616 (0x2330a940)
* Instance of com.adyen.ui.activities.CheckoutActivity$1
|   this$0 = com.adyen.ui.activities.CheckoutActivity@584635456 (0x22d8d440)
|   mDebugUnregister = false
|   mPendingResult = null
* Instance of com.adyen.ui.activities.CheckoutActivity
|   static CREDIT_CARD_FRAGMENT = 1
|   static PAYMENT_METHODS = java.lang.String@583126304 (0x22c1cd20)
|   static PAYMENT_METHOD = java.lang.String@583127136 (0x22c1d060)
|   static GIROPAY_FRAGMENT = 4
|   static CARD_HOLDER_NAME_REQUIRED = java.lang.String@583130048 (0x22c1dbc0)
|   static ONE_CLICK = java.lang.String@583098208 (0x22c15f60)
|   static AMOUNT = java.lang.String@583089760 (0x22c13e60)
|   static $staticOverhead = byte[120]@583884801 (0x22cd6001)
|   static PREFERED_PAYMENT_METHODS = java.lang.String@583126080 (0x22c1cc40)
|   static LOADING_SCREEN_FRAGMENT = 11
|   static TAG_CREDIT_CARD_FRAGMENT = java.lang.String@583095520 (0x22c154e0)
|   static ISSUER_SELECTION_FRAGMENT = 2
|   static FRAGMENT = java.lang.String@1879084424 (0x70008d88)
|   static SEPA_DIRECT_DEBIT_FRAGMENT = 3
|   static PAYMENT_METHOD_SELECTION_FRAGMENT = 0
|   static TAG = java.lang.String@590131296 (0x232cb060)
|   backButtonDisabled = false
|   context = com.adyen.ui.activities.CheckoutActivity@584635456 (0x22d8d440)
|   currentFragment = 2
|   uiFinalizationIntent = com.adyen.ui.activities.CheckoutActivity$1@589182336 (0x231e3580)
|   mCreated = true
|   mFragments = android.support.v4.app.FragmentController@589128864 (0x231d64a0)
|   mHandler = android.support.v4.app.FragmentActivity$1@589078176 (0x231c9ea0)
|   mNextCandidateRequestIndex = 0
|   mPendingFragmentActivityResults = android.support.v4.util.SparseArrayCompat@589182368 (0x231e35a0)
|   mReallyStopped = true
|   mRequestedPermissionsFromFragment = false
|   mResumed = false
|   mRetaining = false
|   mStopped = true
|   mStartedActivityFromFragment = false
|   mStartedIntentSenderFromFragment = false
|   mExtraDataMap = android.support.v4.util.SimpleArrayMap@589182400 (0x231e35c0)
|   mActionBar = com.android.internal.app.WindowDecorActionBar@588792864 (0x23184420)
|   mActivityInfo = android.content.pm.ActivityInfo@589087872 (0x231cc480)
|   mActivityTransitionState = android.app.ActivityTransitionState@589180608 (0x231e2ec0)
|   mAllLoaderManagers = android.util.ArrayMap@589182432 (0x231e35e0)
|   mApplication = nl.beelen.business.BeelenApplication@584859488 (0x22dc3f60)
|   mCalled = true
|   mChangeCanvasToTranslucent = false
|   mChangingConfigurations = false
|   mCheckedForLoaderManager = true
|   mComponent = android.content.ComponentName@589128880 (0x231d64b0)
|   mConfigChangeFlags = 0
|   mContainer = android.app.Activity$1@589128896 (0x231d64c0)
|   mContext = null
|   mCurrentConfig = android.content.res.Configuration@589105968 (0x231d0b30)
|   mDecor = null
|   mDefaultKeyMode = 0
|   mDefaultKeySsb = null
|   mDestroyed = true
|   mDoReportFullyDrawn = false
|   mEmbeddedID = null
|   mEnableDefaultActionBarUp = false
|   mEnterTransitionListener = android.app.SharedElementCallback$1@1889119472 (0x7099acf0)
|   mExitTransitionListener = android.app.SharedElementCallback$1@1889119472 (0x7099acf0)
|   mFinished = true
|   mFragments = android.app.FragmentManagerImpl@589106080 (0x231d0ba0)
|   mHandler = android.os.Handler@589182464 (0x231e3600)
|   mIdent = 400078795
|   mInstanceTracker = android.os.StrictMode$InstanceTracker@589128912 (0x231d64d0)
|   mInstrumentation = android.app.Instrumentation@584845040 (0x22dc06f0)
|   mIntent = android.content.Intent@589180672 (0x231e2f00)
|   mIsFullFlag = false
|   mLastNonConfigurationInstances = null
|   mLoaderManager = null
|   mLoadersStarted = false
|   mMainThread = android.app.ActivityThread@583020912 (0x22c03170)
|   mManagedCursors = java.util.ArrayList@589182496 (0x231e3620)
|   mManagedDialogs = null
|   mMenuInflater = android.view.MenuInflater@589182528 (0x231e3640)
|   mParent = null
|   mReferrer = java.lang.String@589182560 (0x231e3660)
|   mResultCode = 0
|   mResultData = null
|   mResumed = false
|   mSearchManager = null
|   mStartedActivity = false
|   mStopped = true
|   mTemporaryPause = false
|   mTitle = java.lang.String@584834400 (0x22dbdd60)
|   mTitleColor = 0
|   mTitleReady = true
|   mToken = android.os.BinderProxy@588949184 (0x231aa6c0)
|   mTranslucentCallback = null
|   mUiThread = java.lang.Thread@1971052472 (0x757bdfb8)
|   mVisibleBehind = false
|   mVisibleFromClient = true
|   mVisibleFromServer = false
|   mVoiceInteractor = null
|   mWindow = com.android.internal.policy.impl.HwPhoneWindow@585535648 (0x22e690a0)
|   mWindowAdded = true
|   mWindowManager = android.view.WindowManagerImpl@589160064 (0x231dde80)
|   mInflater = com.android.internal.policy.impl.HwPhoneLayoutInflater@589082480 (0x231caf70)
|   mOverrideConfiguration = null
|   mResources = android.content.res.HwResources@584591840 (0x22d829e0)
|   mTheme = android.content.res.Resources$Theme@589160096 (0x231ddea0)
|   mThemeResource = 2131689472
|   mBase = android.app.ContextImpl@589088000 (0x231cc500)
* Excluded Refs:
| Field: android.view.inputmethod.InputMethodManager.mNextServedView
| Field: android.view.inputmethod.InputMethodManager.mServedView
| Field: android.view.inputmethod.InputMethodManager.mServedInputConnection
| Field: android.view.inputmethod.InputMethodManager.mCurRootView
| Field: android.animation.LayoutTransition$1.val$parent
| Field: android.view.textservice.SpellCheckerSession$1.this$0
| Field: android.support.v7.internal.widget.ActivityChooserModel.mActivityChoserModelPolicy
| Field: android.widget.ActivityChooserModel.mActivityChoserModelPolicy
| Field: android.accounts.AccountManager$AmsTask$Response.this$1
| Field: android.media.MediaScannerConnection.mContext
| Field: android.os.UserManager.mContext
| Field: android.media.AudioManager$1.this$0
| Field: android.widget.Editor$Blink.this$0
| Field: android.net.ConnectivityManager.sInstance
| Field: android.view.Choreographer$FrameDisplayEventReceiver.mMessageQueue (always)
| Static field: android.text.TextLine.sCached
| Thread:FinalizerWatchdogDaemon (always)
| Thread:main (always)
| Thread:LeakCanary-Heap-Dump (always)
| Class:java.lang.ref.WeakReference (always)
| Class:java.lang.ref.SoftReference (always)
| Class:java.lang.ref.PhantomReference (always)
| Class:java.lang.ref.Finalizer (always)
| Class:java.lang.ref.FinalizerReference (always)

**Comment by timon-langlotz** [comment] 2017-09-29 11:12
Hi @RikNorakomi,

thank you for reporting this issue. We are aware of an issue with memory leaks caused by references to Contexts/Views. We are also already working on a fix to prevent this in the future. 

We'll update this issue once the problem is resolved.

Kind regards,
Timon

**Comment by timon-langlotz** [comment] 2018-07-19 15:09
Hi @RikNorakomi,

Memory leaks should be fixed with the latest version (2.0.0 or higher) of our SDK!

Cheers,
Timon

**Closed by timon-langlotz** 2018-07-19 15:09 UTC
