### ISSUE TITLE
Localization does not seem to work fully

### ISSUE THREAD

**Issue by erik-kallen** [Adyen/adyen-android#680] opened 2022-04-29 08:00 UTC
**Describe the bug**

I'm trying to configure the UI to use the Swedish locale:

```
Locale locale = new Locale('sv', 'SE');
CardConfiguration cardConfiguration = new CardConfiguration.Builder(context, clientKey)
    .setShopperLocale(locale)
    .build();

DropInConfiguration.Builder configuration = new DropInConfiguration.Builder(getReactApplicationContext(), MyService.class, clientKey)
    .setAmount(amount)
    .setEnvironment(environment)
    .setSkipListWhenSinglePaymentMethod(true)
    .addCardConfiguration(cardConfiguration)
    .setShopperLocale(locale)
    .build();

DropIn.startPayment(activity, paymentMethods, configuration, null)
```

When I do this, I get the following UI:

![image](https://user-images.githubusercontent.com/688028/165905978-a452c4c1-9c34-4056-910b-574833edf05a.png)

As you can see, some fields are being correctly translated ("Expiry date" is correctly translated to "Utgångsdatum", but other fields such as "card number" and the validation messages are not.

**Comment by jreij** [comment] 2022-04-29 08:21
Hi, thanks for reaching out. This is very weird indeed, these strings are all translated and all in the [same xml file](https://github.com/Adyen/adyen-android/blob/develop/card/src/main/res/values/strings.xml) even.

Which version of Drop-in are you using? And is the app built in React Native?
Moreover, can you try to type in your IDE one of the strings that are not working for you, then Ctrl+Click on it? For example `R.string.checkout_card_number_hint`:

![image](https://user-images.githubusercontent.com/9079915/165908651-d7064c1d-c194-4006-aea5-a9580f079c15.png)

Wondering if you can see the Swedish translation as well.

**Comment by jreij** [comment] 2022-04-29 10:34
I think this is related to React Native, we haven't faced this issue with native apps and I don't have much experience with RN but I can see some issues caused by 3rd party libraries, for example [react-native-i18n](https://github.com/AlexanderZaytsev/react-native-i18n/issues/209). Are you using this library or some other localization libraries?

**Comment by erik-kallen** [comment] 2022-04-29 11:20
I also just checked with locale pl-PL. Same effect, only the expiry date and pay button get translated.

**Comment by erik-kallen** [comment] 2022-04-29 11:44
Debugging the code, I can see that the hints for the expiry date and security code (which might work, it's hard to know if the text "CVC / CVV" has been translated) are handled differently from the other localizations.

It seems that the expiry date (and security code) is set with

```
binding.textInputLayoutSecurityCode.setHint(R.string.checkout_card_security_code_hint)
```

but the others are just fetched from the style.

Unfortunately I do not know enough about Android to know why this would cause the behavior, but it is something to go on.

**Comment by jreij** [comment] 2022-05-02 11:33
Thanks for your investigation! I did find out a similar issue that might fix your problem but we can't be sure until we test it. I linked the pull request to this issue and the fix will be included in the next release (`4.6.0`) so you can test it again then. 

You can even checkout the `v4` branch after we merge the linked PR and manually include the SDK on your local development machine if you're eager to test before we release.

**Comment by erik-kallen** [comment] 2022-05-02 13:07
Thank you!

What is the timeframe for the 4.6 release?

**Comment by jreij** [comment] 2022-05-03 08:06
Hopefully in a few weeks 🤞

**Comment by erik-kallen** [comment] 2022-05-04 21:01
Nice!

Does that other PR also address the validation messages? From a quick glance it does not seem like it does.

**Comment by jreij** [comment] 2022-05-05 08:28
It does indeed! You just won't see the string references in the PR because they come from another class internally.

**Comment by erik-kallen** [comment] 2022-05-06 07:25
Nice, then I will check in a few weeks

**Comment by jreij** [comment] 2022-05-12 13:14
FYI we released [version 4.6.0](https://github.com/Adyen/adyen-android/releases/tag/4.6.0) yesterday, which might fix the issue you are facing 🙂

**Comment by erik-kallen** [comment] 2022-05-17 09:08
This appears to have made it work even less (though IMO it behaves slightly better).

After upgrading to 4.6.0, it only translates the pay button, none of the inputs.

![image](https://user-images.githubusercontent.com/688028/168774646-cbc0bd31-49fc-4888-9dbf-081ac1715d66.png)

**Comment by jreij** [comment] 2022-05-17 16:09
At least it's consistently broken now 😅 
Strange case indeed, we were not handling all strings in the same way inside the component, and now that we fixed the wrong ones it turned out that they were the ones working for you. I have tested this with a react native developer but we couldn't reproduce it. I will let you know if I can think of other ways to troubleshoot this.

**Comment by erik-kallen** [comment] 2022-05-18 08:46
The problem seems to have been that I did not change the locale in the CardConfiguration. When I changed that (and used 4.6.0), it seems to work. Thank you.

**Comment by jreij** [comment] 2022-05-18 11:34
Ok that's great to hear! Let me know if you have any more issues, closing this for now.

**Closed by jreij** 2022-05-18 11:34 UTC
