### ISSUE TITLE
Disable "**sepa direct debit**" choice

### ISSUE THREAD

**Issue by FabioCappelliSpot** [Adyen/adyen-android#43] opened 2018-10-22 08:20 UTC
Hi,
How can I disable "**sepa direct debit**" choice when start CheckoutActivity without implements custom integrations?

I see in latest version there is a field _blockedPaymentMethods = ['sepadirectdebit']_ to achieve it but I use api version v32.
https://docs.adyen.com/api-explorer/#/PaymentSetupAndVerificationService/v32/paymentSession

Thanks
 
Fabio

**Comment by timon-langlotz** [comment] 2018-11-27 10:12
Duplicate of #44.

**Closed by timon-langlotz** 2018-11-27 10:12 UTC
