### ISSUE TITLE
Project set up

### ISSUE THREAD

**Issue by BartlomiejFrankow** [Adyen/adyen-android#1479] opened 2024-02-19 10:56 UTC
**Describe the bug**
There are no information at all about how and where to put important keys. Currently, after few hours of search, I found the proper place. It's inside `default.locale.gradle`, but why can't you simply mention this inside of README file?
Additionally, if you won't add `MERCHANT_SERVER_URL` you got errors like `API call failed`. 

Inside `adyen-android` application logic for `MERCHANT_SERVER_URL` is in `NetworkModule` and looks like this:
```
private val BASE_URL = if (CheckoutApiService.isRealUrlAvailable()) {
        BuildConfig.MERCHANT_SERVER_URL
    } else {
        "http://myserver.com/my/endpoint/"
    }
```

So, if we won't add `MERCHANT_SERVER_URL` requests won't work. At the same time iOS team did same integration, and they don't need to paste `MERCHANT_SERVER_URL`. So I asked them how code looks on their side for this key, and it looks like this:
```
internal enum DemoCheckoutAPIEnvironment: String, AnyAPIEnvironment, CaseIterable {
    
    case beta, test, local
    
    internal var baseURL: URL {
        switch self {
        case .beta:
            return URL(string: "https://checkout-beta.adyen.com/checkout/v\(version)")!
        case .test:
            return URL(string: "https://checkout-test.adyen.com/v\(version)")!
        case .local:
            return URL(string: "http://localhost:8080/checkout/v\(version)")!
        }
    }

    internal var version: Int { ConfigurationConstants.current.apiVersion }
    
}
```

My question is: "Why Android don't have this code?"
So I paste:
```
buildConfigField "String", "MERCHANT_SERVER_URL", "\"https://checkout-test.adyen.com/v71/\""
```
... and now request are successful. 

**Expected behavior**
1. Please add description where to put credential values - `default.locale.gradle`
2. Add similar to iOS code for `MERCHANT_SERVER_URL`

**Comment by BartlomiejFrankow** [comment] 2024-02-19 11:09
There is an option to find `MERCHANT_SERVER_URL` inside documentation, but this is not visible for sure. [Step 2 Android payment request example.](https://docs.adyen.com/online-payments/build-your-integration/?platform=Android&integration=Drop-in&version=5.2.0#sessions-android)

**Comment by ozgur00** [comment] 2024-02-20 09:56
Hi @BartlomiejFrankow, for security reasons we suggest having a middleware between your app and checkout endpoint so that you can store your sensitive information securely there. That is the reason we leave that field unset so you can add your endpoint url to use it. 

The following code segment that you shared is part of the example-app, which is to guide SDK users on how to set things up and integrate with the Adyen SDK on your app.
```kotlin
private val BASE_URL = if (CheckoutApiService.isRealUrlAvailable()) {
        BuildConfig.MERCHANT_SERVER_URL
    } else {
        "http://myserver.com/my/endpoint/"
    }
 ```
We will take your suggestion of adding an explanation for the `MERCHANT_SERVER_URL` in README file and having `https://checkout-test.adyen.com/<version>` as default into account. Thanks for your input!

**Comment by ozgur00** [comment] 2024-02-20 09:58
Duplicate of #1401

**Closed** 2024-02-20 11:58 UTC
Labels: Duplicate

**Comment by jreij** [comment] 2024-03-11 15:14
HI @BartlomiejFrankow, we just merged a PR that will improve the usability of the testing app. Please take a look at the [readme](https://github.com/Adyen/adyen-android/tree/develop/example-app#readme).

However note that your current setup will break, sorry for that 😄
To migrate, go to `example-app/local.gradle` and follow these steps:
- Rename `API_KEY_HEADER_NAME` to `AUTHORIZATION_HEADER_NAME`.
- Rename `CHECKOUT_API_KEY` to `AUTHORIZATION_HEADER_VALUE`.
- Remove `SHOPPER_REFERENCE` line. It will now default to `"test-android-components"`, you can change that value in the settings screen if you want.
- Remove unnecessary quote symbol escaping: `"\"SOME_VALUE\""` can be replaced with `'"SOME_VALUE"'`.

Let us know if you have any comments or need more help with this.
