### ISSUE TITLE
3DS2 test cards don't give user feedback/error

### ISSUE THREAD

**Issue by RuudBurger** [Adyen/adyen-android#65] opened 2019-05-01 13:53 UTC
Like mentioned here: https://github.com/Adyen/adyen-android/issues/41#issuecomment-488281268 

When using the drop-in UI while testing the 3DS functionality there is no error or feedback for the user. I don't know if this is only an issue with test cards, but even then I would at least expect a "invalid payment"-error.

Like mentioned in the above ticket. non-3DS testing cards work like expected with proper error handling, the 3DS cards work also.

**Comment by andre-sonect** [comment] 2019-05-02 09:13
Having a similar issue. The 3DS or 3DS2 test cards not showing any error and not able to test them :)
Critical issue since we rely on alot of users that use 3DS cards.

**Comment by ran-haveshush** [comment] 2019-05-02 09:29
Hi @RuudBurger and @andre-sonect,

Currently the Checkout 3DS2 support is opt-in so in order to add it, please add the following dependency: `implementation "com.adyen.checkout:threeds:$versions.checkout_sdk"`

As for the lack of documentation you are absolutely right we will add that to the README file.

Please report back if that solved the issue.

Cheers :)

**Comment by andre-sonect** [comment] 2019-05-02 09:34
@ran-haveshush Thanks for the information man!

**Comment by andre-sonect** [comment] 2019-05-02 10:05
@ran-haveshush getting a `com.adyen.threeds2.exception.InvalidInputException: acsSignedContent could not be verified.` due to `Caused by: java.security.cert.CertificateException: Error verifying certificate chain`

**Comment by ran-haveshush** [comment] 2019-05-02 10:22
@andre-sonect Does it happen when testing on Android API level < 24?

If so it is a known issue with the Adyen's 3DS2 Sim server certification been on version 1 and not 3.
We will fix this in the near future and it will not influence live transactions, since the schemes servers certification are all version 3 certs.

BTW this is the [3DS2 SDK troubleshooting](https://github.com/Adyen/adyen-3ds2-android/blob/master/TROUBLESHOOTING.md) page.

**Comment by andre-sonect** [comment] 2019-05-02 10:29
@ran-haveshush Yes indeed because of being version 1. Okay I will pass that along to the team.

**Comment by lbenedetto** [comment] 2019-06-06 13:54
Including the threeds module just makes our app crash when a user uses a 3ds card instead of failing silently. Additionally, it makes normal cards fail silently.

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/adyen/checkout/nfc/NfcCardReader$Error;

And then when I include the nfc library (which I should not have to do), the app crashes because threeds is trying to do something it shouldn't on the main thread.

```
java.lang.IllegalStateException: Must not be called on the main application thread
        at com.google.android.gms.common.internal.Preconditions.checkNotMainThread(Unknown Source:51)
        at com.google.android.gms.common.internal.Preconditions.checkNotMainThread(Unknown Source:48)
        at com.google.android.gms.tasks.Tasks.await(Unknown Source:24)
        at com.adyen.threeds2.internal.c.a.c.h.a(:4)
        at com.adyen.threeds2.internal.c.a.c.h$b.b(:2)
        at com.adyen.threeds2.internal.c.a.c.h$b.b(:1)
        at com.adyen.threeds2.internal.c.a.d.a(:2)
        at com.adyen.threeds2.internal.c.b.a(:13)
        at com.adyen.threeds2.internal.c.b.<init>(:5)
        at com.adyen.threeds2.internal.c.b.a(:2)
        at com.adyen.threeds2.internal.j.initialize(:10)
        at com.adyen.checkout.threeds.Card3DS2Authenticator.createFingerprint(Card3DS2Authenticator.java:107)
        at com.adyen.checkout.threeds.Card3DS2Authenticator.createFingerprint(Card3DS2Authenticator.java:82)
        at com.adyen.checkout.ui.internal.card.CardDetailsActivity.onAuthenticationDetailsRequired(CardDetailsActivity.java:346)
        at com.adyen.checkout.core.internal.AuthenticationManager.dispatch(AuthenticationManager.java:24)
        at com.adyen.checkout.core.internal.AuthenticationManager.dispatch(AuthenticationManager.java:16)
        at com.adyen.checkout.core.internal.BaseManager.checkDispatch(BaseManager.java:46)
        at com.adyen.checkout.core.internal.BaseManager.setData(BaseManager.java:37)
        at com.adyen.checkout.core.internal.PaymentHandlerImpl$8.run(PaymentHandlerImpl.java:464)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6923)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)
```

**Comment by przan** [comment] 2019-07-04 12:58
I have a similar issues with 3DS and ProGuard: https://github.com/Adyen/adyen-android/issues/82

**Comment by przan** [comment] 2019-07-04 13:11
I've also noticed, that nothing happens after pressing "Pay" for SDK 2.4.5 and 3DS1 cards: 5212 3456 7890 1234 and 4212 3456 7890 1237. I haven't added `implementation "com.adyen.checkout:threeds:$versions.checkout_sdk"` because it crashes in my release build

**Comment by caiofaustino** [comment] 2019-07-11 09:36
I'm closing this issue since it became a bit of a mix of different issues with 3DS2, which are mostly solved afaik. If anyone still has any problem feel free to open a new one.

**Closed by caiofaustino** 2019-07-11 09:36 UTC

**Comment by huszarg** [comment] 2019-07-22 08:26
> Including the threeds module just makes our app crash when a user uses a 3ds card instead of failing silently. Additionally, it makes normal cards fail silently.
> 
> java.lang.NoClassDefFoundError: Failed resolution of: Lcom/adyen/checkout/nfc/NfcCardReader$Error;
> 
> And then when I include the nfc library (which I should not have to do), the app crashes because threeds is trying to do something it shouldn't on the main thread.
> 
> ```
> java.lang.IllegalStateException: Must not be called on the main application thread
>         at com.google.android.gms.common.internal.Preconditions.checkNotMainThread(Unknown Source:51)
>         at com.google.android.gms.common.internal.Preconditions.checkNotMainThread(Unknown Source:48)
>         at com.google.android.gms.tasks.Tasks.await(Unknown Source:24)
>         at com.adyen.threeds2.internal.c.a.c.h.a(:4)
>         at com.adyen.threeds2.internal.c.a.c.h$b.b(:2)
>         at com.adyen.threeds2.internal.c.a.c.h$b.b(:1)
>         at com.adyen.threeds2.internal.c.a.d.a(:2)
>         at com.adyen.threeds2.internal.c.b.a(:13)
>         at com.adyen.threeds2.internal.c.b.<init>(:5)
>         at com.adyen.threeds2.internal.c.b.a(:2)
>         at com.adyen.threeds2.internal.j.initialize(:10)
>         at com.adyen.checkout.threeds.Card3DS2Authenticator.createFingerprint(Card3DS2Authenticator.java:107)
>         at com.adyen.checkout.threeds.Card3DS2Authenticator.createFingerprint(Card3DS2Authenticator.java:82)
>         at com.adyen.checkout.ui.internal.card.CardDetailsActivity.onAuthenticationDetailsRequired(CardDetailsActivity.java:346)
>         at com.adyen.checkout.core.internal.AuthenticationManager.dispatch(AuthenticationManager.java:24)
>         at com.adyen.checkout.core.internal.AuthenticationManager.dispatch(AuthenticationManager.java:16)
>         at com.adyen.checkout.core.internal.BaseManager.checkDispatch(BaseManager.java:46)
>         at com.adyen.checkout.core.internal.BaseManager.setData(BaseManager.java:37)
>         at com.adyen.checkout.core.internal.PaymentHandlerImpl$8.run(PaymentHandlerImpl.java:464)
>         at android.os.Handler.handleCallback(Handler.java:873)
>         at android.os.Handler.dispatchMessage(Handler.java:99)
>         at android.os.Looper.loop(Looper.java:193)
>         at android.app.ActivityThread.main(ActivityThread.java:6923)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)
> ```

I have a same issue with Android Adyen SDK 2.4.5 (but it works fine on iOS). Using 3DS2 test card the app crashes with same error "java.lang.IllegalStateException: Must not be called on the main application thread". How did you fix it?

**Comment by gmorales** [comment] 2019-08-23 09:27
> > Including the threeds module just makes our app crash when a user uses a 3ds card instead of failing silently. Additionally, it makes normal cards fail silently.
> > java.lang.NoClassDefFoundError: Failed resolution of: Lcom/adyen/checkout/nfc/NfcCardReader$Error;
> > And then when I include the nfc library (which I should not have to do), the app crashes because threeds is trying to do something it shouldn't on the main thread.
> > ```
> > java.lang.IllegalStateException: Must not be called on the main application thread
> >         at com.google.android.gms.common.internal.Preconditions.checkNotMainThread(Unknown Source:51)
> >         at com.google.android.gms.common.internal.Preconditions.checkNotMainThread(Unknown Source:48)
> >         at com.google.android.gms.tasks.Tasks.await(Unknown Source:24)
> >         at com.adyen.threeds2.internal.c.a.c.h.a(:4)
> >         at com.adyen.threeds2.internal.c.a.c.h$b.b(:2)
> >         at com.adyen.threeds2.internal.c.a.c.h$b.b(:1)
> >         at com.adyen.threeds2.internal.c.a.d.a(:2)
> >         at com.adyen.threeds2.internal.c.b.a(:13)
> >         at com.adyen.threeds2.internal.c.b.<init>(:5)
> >         at com.adyen.threeds2.internal.c.b.a(:2)
> >         at com.adyen.threeds2.internal.j.initialize(:10)
> >         at com.adyen.checkout.threeds.Card3DS2Authenticator.createFingerprint(Card3DS2Authenticator.java:107)
> >         at com.adyen.checkout.threeds.Card3DS2Authenticator.createFingerprint(Card3DS2Authenticator.java:82)
> >         at com.adyen.checkout.ui.internal.card.CardDetailsActivity.onAuthenticationDetailsRequired(CardDetailsActivity.java:346)
> >         at com.adyen.checkout.core.internal.AuthenticationManager.dispatch(AuthenticationManager.java:24)
> >         at com.adyen.checkout.core.internal.AuthenticationManager.dispatch(AuthenticationManager.java:16)
> >         at com.adyen.checkout.core.internal.BaseManager.checkDispatch(BaseManager.java:46)
> >         at com.adyen.checkout.core.internal.BaseManager.setData(BaseManager.java:37)
> >         at com.adyen.checkout.core.internal.PaymentHandlerImpl$8.run(PaymentHandlerImpl.java:464)
> >         at android.os.Handler.handleCallback(Handler.java:873)
> >         at android.os.Handler.dispatchMessage(Handler.java:99)
> >         at android.os.Looper.loop(Looper.java:193)
> >         at android.app.ActivityThread.main(ActivityThread.java:6923)
> >         at java.lang.reflect.Method.invoke(Native Method)
> >         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
> >         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)
> > ```
> 
> I have a same issue with Android Adyen SDK 2.4.5 (but it works fine on iOS). Using 3DS2 test card the app crashes with same error "java.lang.IllegalStateException: Must not be called on the main application thread". How did you fix it?

Also facing same issue. Has anybody solved this?

**Comment by caiofaustino** [comment] 2019-08-23 10:54
> > > Including the threeds module just makes our app crash when a user uses a 3ds card instead of failing silently. Additionally, it makes normal cards fail silently.
> > > java.lang.NoClassDefFoundError: Failed resolution of: Lcom/adyen/checkout/nfc/NfcCardReader$Error;
> > > And then when I include the nfc library (which I should not have to do), the app crashes because threeds is trying to do something it shouldn't on the main thread.
> > > ```
> > > java.lang.IllegalStateException: Must not be called on the main application thread
> > >         at com.google.android.gms.common.internal.Preconditions.checkNotMainThread(Unknown Source:51)
> > >         at com.google.android.gms.common.internal.Preconditions.checkNotMainThread(Unknown Source:48)
> > >         at com.google.android.gms.tasks.Tasks.await(Unknown Source:24)
> > >         at com.adyen.threeds2.internal.c.a.c.h.a(:4)
> > >         at com.adyen.threeds2.internal.c.a.c.h$b.b(:2)
> > >         at com.adyen.threeds2.internal.c.a.c.h$b.b(:1)
> > >         at com.adyen.threeds2.internal.c.a.d.a(:2)
> > >         at com.adyen.threeds2.internal.c.b.a(:13)
> > >         at com.adyen.threeds2.internal.c.b.<init>(:5)
> > >         at com.adyen.threeds2.internal.c.b.a(:2)
> > >         at com.adyen.threeds2.internal.j.initialize(:10)
> > >         at com.adyen.checkout.threeds.Card3DS2Authenticator.createFingerprint(Card3DS2Authenticator.java:107)
> > >         at com.adyen.checkout.threeds.Card3DS2Authenticator.createFingerprint(Card3DS2Authenticator.java:82)
> > >         at com.adyen.checkout.ui.internal.card.CardDetailsActivity.onAuthenticationDetailsRequired(CardDetailsActivity.java:346)
> > >         at com.adyen.checkout.core.internal.AuthenticationManager.dispatch(AuthenticationManager.java:24)
> > >         at com.adyen.checkout.core.internal.AuthenticationManager.dispatch(AuthenticationManager.java:16)
> > >         at com.adyen.checkout.core.internal.BaseManager.checkDispatch(BaseManager.java:46)
> > >         at com.adyen.checkout.core.internal.BaseManager.setData(BaseManager.java:37)
> > >         at com.adyen.checkout.core.internal.PaymentHandlerImpl$8.run(PaymentHandlerImpl.java:464)
> > >         at android.os.Handler.handleCallback(Handler.java:873)
> > >         at android.os.Handler.dispatchMessage(Handler.java:99)
> > >         at android.os.Looper.loop(Looper.java:193)
> > >         at android.app.ActivityThread.main(ActivityThread.java:6923)
> > >         at java.lang.reflect.Method.invoke(Native Method)
> > >         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
> > >         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)
> > > ```
> > 
> > 
> > I have a same issue with Android Adyen SDK 2.4.5 (but it works fine on iOS). Using 3DS2 test card the app crashes with same error "java.lang.IllegalStateException: Must not be called on the main application thread". How did you fix it?
> 
> Also facing same issue. Has anybody solved this?

Have you tried updating to the latest version 2.4.8? What are your dependencies like?

**Comment by gmorales** [comment] 2019-08-23 12:27
> > > > Including the threeds module just makes our app crash when a user uses a 3ds card instead of failing silently. Additionally, it makes normal cards fail silently.
> > > > java.lang.NoClassDefFoundError: Failed resolution of: Lcom/adyen/checkout/nfc/NfcCardReader$Error;
> > > > And then when I include the nfc library (which I should not have to do), the app crashes because threeds is trying to do something it shouldn't on the main thread.
> > > > ```
> > > > java.lang.IllegalStateException: Must not be called on the main application thread
> > > >         at com.google.android.gms.common.internal.Preconditions.checkNotMainThread(Unknown Source:51)
> > > >         at com.google.android.gms.common.internal.Preconditions.checkNotMainThread(Unknown Source:48)
> > > >         at com.google.android.gms.tasks.Tasks.await(Unknown Source:24)
> > > >         at com.adyen.threeds2.internal.c.a.c.h.a(:4)
> > > >         at com.adyen.threeds2.internal.c.a.c.h$b.b(:2)
> > > >         at com.adyen.threeds2.internal.c.a.c.h$b.b(:1)
> > > >         at com.adyen.threeds2.internal.c.a.d.a(:2)
> > > >         at com.adyen.threeds2.internal.c.b.a(:13)
> > > >         at com.adyen.threeds2.internal.c.b.<init>(:5)
> > > >         at com.adyen.threeds2.internal.c.b.a(:2)
> > > >         at com.adyen.threeds2.internal.j.initialize(:10)
> > > >         at com.adyen.checkout.threeds.Card3DS2Authenticator.createFingerprint(Card3DS2Authenticator.java:107)
> > > >         at com.adyen.checkout.threeds.Card3DS2Authenticator.createFingerprint(Card3DS2Authenticator.java:82)
> > > >         at com.adyen.checkout.ui.internal.card.CardDetailsActivity.onAuthenticationDetailsRequired(CardDetailsActivity.java:346)
> > > >         at com.adyen.checkout.core.internal.AuthenticationManager.dispatch(AuthenticationManager.java:24)
> > > >         at com.adyen.checkout.core.internal.AuthenticationManager.dispatch(AuthenticationManager.java:16)
> > > >         at com.adyen.checkout.core.internal.BaseManager.checkDispatch(BaseManager.java:46)
> > > >         at com.adyen.checkout.core.internal.BaseManager.setData(BaseManager.java:37)
> > > >         at com.adyen.checkout.core.internal.PaymentHandlerImpl$8.run(PaymentHandlerImpl.java:464)
> > > >         at android.os.Handler.handleCallback(Handler.java:873)
> > > >         at android.os.Handler.dispatchMessage(Handler.java:99)
> > > >         at android.os.Looper.loop(Looper.java:193)
> > > >         at android.app.ActivityThread.main(ActivityThread.java:6923)
> > > >         at java.lang.reflect.Method.invoke(Native Method)
> > > >         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
> > > >         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)
> > > > ```
> > > 
> > > 
> > > I have a same issue with Android Adyen SDK 2.4.5 (but it works fine on iOS). Using 3DS2 test card the app crashes with same error "java.lang.IllegalStateException: Must not be called on the main application thread". How did you fix it?
> > 
> > 
> > Also facing same issue. Has anybody solved this?
> 
> Have you tried updating to the latest version 2.4.8? What are your dependencies like?

@caiofaustino thanks man. I was using version 2.4.5, I didn't realised that version 2.4.8 even exist. Crash is now solved, I saw that `ThreeDS2Service` is being call now by an `AsyncTask`. :)
