### ISSUE TITLE
com.adyen.checkout.core.exception.CheckoutException: Action component is not loaded

### ISSUE THREAD

**Issue by a178960320** [Adyen/adyen-android#752] opened 2022-08-10 08:15 UTC
we are use adyen android dropin, a crash on pay result back to our app. what should we do to slove this crash.

**Screenshots**
![image](https://user-images.githubusercontent.com/23234724/183850538-93bcd548-2d59-43dc-a72a-21d7e59e465e.png)

2022-08-10 16:04:50.929 16616-16616/com.tap4fun.tgs.demo.gplay E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.tap4fun.tgs.demo.gplay, PID: 16616
    java.lang.Error: FATAL EXCEPTION [main]
    Unity version     : 2019.4.10f1
    Device model      : smartisan OC105
    Device fingerprint: Android/oscar/oscar:7.1.2/N2G47H/1610677912:user/dev-keys
    
    Caused by: java.lang.RuntimeException: Unable to resume activity {com.tap4fun.tgs.demo.gplay/com.adyen.checkout.dropin.ui.DropInActivity}: com.adyen.checkout.core.exception.CheckoutException: Action component is not loaded
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3645)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3685)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2947)
        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4737)
        at android.app.ActivityThread.-wrap19(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1670)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:159)
        at android.app.ActivityThread.main(ActivityThread.java:6378)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1099)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
     Caused by: com.adyen.checkout.core.exception.CheckoutException: Action component is not loaded
        at com.adyen.checkout.dropin.ActionHandler.handleIntent(ActionHandler.kt:81)
        at com.adyen.checkout.dropin.ActionHandler.handleRedirectResponse(ActionHandler.kt:73)
        at com.adyen.checkout.dropin.ui.DropInActivity.handleIntent(DropInActivity.kt:477)
        at com.adyen.checkout.dropin.ui.DropInActivity.onNewIntent(DropInActivity.kt:237)
        at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1224)
        at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1236)
        at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:3017)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3614)

**Comment by OscarSpruit** [comment] 2022-08-10 08:45
Hi, could you provide more detailed steps to reproduce it? I'm trying to reproduce it, but without luck so far

**Comment by a178960320** [comment] 2022-08-10 08:59
i'm use alipay hk
![Screenshot_2022-08-10-16-52-13-047_TgsApe](https://user-images.githubusercontent.com/23234724/183859446-eaa11485-d0ad-4422-ae05-68be53d896a4.png)

in the pay page,i'm touch cancelled or authorised
![Screenshot_2022-08-10-16-52-51-442_TgsApe](https://user-images.githubusercontent.com/23234724/183859785-9a9371d2-8307-4c38-bbfe-ccfdddda1fcd.png)

then redirect url is loaded,system tip, go back our app
![Screenshot_2022-08-10-16-53-03-085_TgsApe](https://user-images.githubusercontent.com/23234724/183860105-2952c12d-3e72-4b51-a071-833f0d1bbbfc.png)

touch open item, a crash happen
![Screenshot_2022-08-10-16-53-23-260_TgsApe](https://user-images.githubusercontent.com/23234724/183860517-fe9fbf06-1acc-4c50-8825-a4b972e06dce.png)

**Comment by a178960320** [comment] 2022-08-10 09:04
Can I know when this method will be called? Need to trigger manually?
<img width="938" alt="image" src="https://user-images.githubusercontent.com/23234724/183861707-964cc2c4-6af7-4b41-b7f2-813e80e5978b.png">

**Comment by a178960320** [comment] 2022-08-10 11:28
i find Class DropInActivity, onCreate function call two time,

1. i'm call " DropIn.startPayment"
2.redirect my app also call onCreate.

<img width="838" alt="image" src="https://user-images.githubusercontent.com/23234724/183889746-deebb707-465c-4b34-9f2b-ff8b6d9298fb.png">

the second call "onCreate"，then call "handleIntent"

<img width="817" alt="image" src="https://user-images.githubusercontent.com/23234724/183889967-32b5bc07-e794-4165-91cc-356d409c7ef7.png">

actionHandler loadedComponent is null
<img width="630" alt="image" src="https://user-images.githubusercontent.com/23234724/183890033-4bfc19ba-d802-4ade-9691-cf17b3617cca.png">

then throw checkoutException
<img width="846" alt="image" src="https://user-images.githubusercontent.com/23234724/183890307-c1faf78f-c9dd-4df8-9115-bdf28d9ac2f4.png">

**Comment by OscarSpruit** [comment] 2022-08-10 11:38
We have had a similar issue before and fixed it, which version of the Drop-In SDK are you using?

**Comment by a178960320** [comment] 2022-08-10 11:38
4.0.0

**Comment by OscarSpruit** [comment] 2022-08-10 11:44
In `4.1.0` we released a fix for this issue, so updating the SDK should solve your problem. I would advise to update to the latest version of the SDK though, but that could be a bit more work

**Comment by a178960320** [comment] 2022-08-11 05:57
thx, i'm update to 4.1.0, the problem is solved.

**Comment by a178960320** [comment] 2022-08-11 06:03
I seem to have another problem, I can't see the pay button in landscape orientation,I've swiped up, but I can't move when I reach the top

![image](https://user-images.githubusercontent.com/23234724/184073035-57f19f62-e129-45ba-9d94-966d0e42ea0d.png)

**Comment by OscarSpruit** [comment] 2022-08-11 08:43
Oh I wasn't aware of that issue being in 4.1.0, but this has been fixed in a later release. Since 4.1.0 we have resolved multiple issues. You might run into one of these issues if you're not updating to the latest version, so I would really advise to update to the latest version (which is 4.7.1 at the moment).

**Comment by a178960320** [comment] 2022-08-11 08:54
can you tell me what version slove this problem? I want to access ayen with minimal changes.. plz .

**Comment by OscarSpruit** [comment] 2022-08-11 11:11
Since 4.6.0 the Card Component is fully scrollable. However, all changes since 4.1.0 have been internal, so you don't have to change any code when updating to even the latest. So once again, I would advise to update to 4.7.1 to avoid running into any other issues.

One thing to note: since 4.3.0 `DropInConfiguration`  now initialized with `Environment.TEST` by default instead of `Environment.EUROPE`

**Closed** 2022-08-12 01:50 UTC
