### ISSUE TITLE
Restore DropIn after app gets killed

### ISSUE THREAD

**Issue by tinsukE** [Adyen/adyen-android#151] opened 2019-12-17 08:54 UTC
We are getting crash reports with the following stack trace:
```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.tiqets.tiqetsapp/com.adyen.checkout.dropin.ui.DropInActivity}: java.lang.IllegalStateException: intent.getParcelableExtr…ROP_IN_CONFIGURATION_KEY) must not be null
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3374)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3513)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2109)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7682)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

Caused by java.lang.IllegalStateException: intent.getParcelableExtr…ROP_IN_CONFIGURATION_KEY) must not be null
       at com.adyen.checkout.dropin.ui.DropInActivity.onCreate(DropInActivity.java:140)
       at android.app.Activity.performCreate(Activity.java:7815)
       at android.app.Activity.performCreate(Activity.java:7804)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1318)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3349)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3513)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2109)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7682)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```
It has happened from Android 5.1.1 to 9, so I don't believe they're version related.

We are starting the payment like so:
```
val paymentMethodsApiResponse = PaymentMethodsApiResponse.SERIALIZER.deserialize(
    JSONObject(paymentMethodData)
)

@Suppress("ConstantConditionIf")
val environment = if (BuildUtil.PRODUCTION) Environment.EUROPE else Environment.TEST
val locale = localeRepository.currentLocale

val cardConfiguration = CardConfiguration.Builder(
    locale,
    environment,
    context.getString(R.string.adyen_public_key)
)
    .setShowStorePaymentField(false)
    .build()

val resultIntent = PaymentResultActivity.newIntent(...)

val dropInConfiguration = DropInConfiguration.Builder(
    context,
    resultIntent,
    TiqetsDropInService::class.java
)
    .addCardConfiguration(cardConfiguration)
    .apply {
        setShopperLocale(locale)
        createAdyenAmount()?.let {
            setAmount(it)
        }
    }
    .build()

DropIn.startPayment(activity, paymentMethodsApiResponse, dropInConfiguration)
```
We don't have information about the payments themselves, but let me know if you need more information.

**Comment by caiofaustino** [comment] 2019-12-17 08:57
Hmm interesting, that's the same issue as #146 

Do you know if that issue happens immediately when starting the payment or after some time in the flow? I pushed a fix for this on 3.6.0, but it only suppresses the crash for an Error message, I'd like to know more about the root cause for this.

**Comment by tinsukE** [comment] 2019-12-17 10:09
Sorry for the report duplication.

Checking Firebase Crashlytics, it seems that the crash happens when the DropInActivity is launched, but the report's timestamp is only accurate to the minute, so it seems that the crash happens within 1min of the Activity being viewed, with a few outliars:
1. Once the crash happened 6min after the DropInActivity was viewed
2. Once the crash happened 1h after the DropInActivity was viewed (and was the last viewed Activity), when the App was re-opened.
3. Once the crash happened after DropInActivity seemed to finish and our caller Activity was viewed.

Your reasoning that Intents created via `DropInActivity.createIntent()` (called from `DropIn.startPayment()`) seems solid, until you thing about DropInActivity having an intent filter for handling returns from checkout redirect.

If the DropInActivity is not at the top of the activity stack, and the user is redirected back to the App, the App crashes since a new DropInActivity will be launched ([DropInActivity.onNewIntent() won't be called](https://developer.android.com/reference/android/app/Activity#onNewIntent(android.content.Intent))), but it won't have the configuration in the Intent extras. This can be reproduced by:
- Disable your default browser's Custom Tabs support (I used Firefox)
- Launch your App
- Start a checkout with a redirect type of payment (I used iDeal)
- When at the browser, kill your App
- Still at the browser, finish the payment (I cancelled it)
- The App is launched and crashes.

I'm not sure if only this "kill the App during a redirect payment" scenario triggers the crash. But it can happen, and the user could successfully finish a payment this way.

If DropInActivity would persist the configuration to disk, this could be avoided. But it'd have other drawbacks like having to make sure that the caller App still can handle the result Intent (the App can be updated while the user is in the browser and have renamed the class that handles the result Intent).

**Comment by caiofaustino** [comment] 2019-12-17 15:24
No worries, I just pointed out the duplication because its probably an issue on our side.

So yeah it makes sense that the issue would happen in that scenario if the process gets killed completely, and indeed there is not really a way for for us to store the Configuration to disk. So that is 1 scenario, although I'm not sure how likely it is that it would happen.

I retested the flow you mentioned but with killing the Activity in the background with the `Don't keep activities` instead of manually swiping the app, and it works as I expected with the `onSaveInstanceState` flow. So I'm trying to figure out if there is any other scenario where the Activity would be completely destroyed, with a new instance being created from the Browser intent without restoring the old state, but without killing the app process. Like a weird activity stack scenario or something. That would be a different issue that maybe we could tackle.

If you have any ideas let me know, I'll try to investigate a bit more.

But in the mean time, the fix on `3.6.0` should avoid the crash, but would still fail the payment UI flow.

**Comment by tinsukE** [comment] 2019-12-17 16:33
I just figured out another, much more likely to happen, way to reproduce the crash:
- Again, with Custom Tabs disabled
- Launch your App
- Start a checkout flow using a redirect payment method
- From the browser, return to your App
- Dismiss the DropIn
- Go back to the browser
- Complete the payment (or cancel) 
- The App crashes

This could be caused by an user that gives up on the payment and later on finds the payment tab in their browser and cancels the payment. 

It could also happen if the user is experiencing unstable connection and, after triggering a payment in the browser that will take some to complete (or cancel), goes back to your App and (maybe accidentally) dismisses the DropIn. The browser payment can eventually resolve and redirect to the App, which would crash because the DropIn will be relaunched from scratch, not from onNewIntent().

**Comment by tinsukE** [comment] 2019-12-17 16:33
And of course not crashing with 3.6.0 is better than the current situation, but those faulty scenarios that would have caused a crash before, will keep happening, just silently.

**Comment by caiofaustino** [comment] 2019-12-18 11:59
Yeah that's a good point too. I've discussed a bit with my colleagues and we agree we should probably have a mechanism to kind of "ask" the app to recreate the DropIn in those scenarios and then continue the flow. So we will put this in the backlog as something we still need to discuss.

But for now, the recommendation is to rely on the [Server notifications](https://docs.adyen.com/development-resources/notifications), as that is a better source of truth than the front end result. So even if the user sees an error at first, you can trigger a message later saying that the payment was received for example.

I imagine this is enough of an edge case that it won't be very common, but keep us posted if you see it happening more often, and we will already start to work on improving this case.

**Closed** 2020-01-20 13:41 UTC
