### ISSUE TITLE
3DS2 and Gradle 8

### ISSUE THREAD

**Issue by christianfindsen** [Adyen/adyen-android#1233] opened 2023-06-13 09:00 UTC
**The issue**
After we upgraded to Gradle 8 the 3DS2 challenge is failing when trying to do the challenge
A further investigation show that the error is happining in `Adyen3DS2Component::challengeShopper`
Looking into the logs it's saying `Error starting challenge` and with a breakpoint in the above class we get a `com.adyen.threeds2.exception.InvalidInputException: Invalid challengeParameters.` 

**To Reproduce**
Upgrade to gradle 8 and do a purchase with a test card prompting for 3DS2

**Additional context**
If we downgrade to gradle 7.4.2 we get expected behavior

We are running components 4.12.0

**Comment by OscarSpruit** [comment] 2023-06-14 13:58
Hi @christianfindsen thank you for opening this issue! I have been trying to reproduce it without luck. Could you share the entire stacktrace of the exception you were able to intercept?

**Comment by mikkoville** [comment] 2023-06-16 07:11
@OscarSpruit we are hitting the same issue here after update to AGP 8.

it seems it happens only for builds that have Proguard/r8 & minify enabled.

For builds that have no proguard on it works. Will report if I can dig more details.

Note that we are not using adyen-android. We are using [adyen-3ds2-android](https://github.com/Adyen/adyen-3ds2-android). Are these both libraries using some shared code?

**Comment by mikkoville** [comment] 2023-06-16 08:11
Created an issue also on the original repo:
https://github.com/Adyen/adyen-3ds2-android/issues/53

**Comment by christianfindsen** [comment] 2023-06-16 08:22
@mikkoville's bugreport that he mentions above is exactly the same issue we are facing.

**Comment by christianfindsen** [comment] 2023-06-16 09:30
@OscarSpruit Here is the stacktrace:

`om.adyen.checkout.core.exception.CheckoutException: Error starting challenge
                                                                                                    	at com.adyen.checkout.adyen3ds2.Adyen3DS2Component.challengeShopper(Adyen3DS2Component.kt:298)
                                                                                                    	at com.adyen.checkout.adyen3ds2.Adyen3DS2Component.handleActionSubtype(Adyen3DS2Component.kt:144)
                                                                                                    	at com.adyen.checkout.adyen3ds2.Adyen3DS2Component.handleActionInternal(Adyen3DS2Component.kt:136)
                                                                                                    	at com.adyen.checkout.components.base.BaseActionComponent.handleAction(BaseActionComponent.java:56)
                                                                                                    	at com.adyen.checkout.adyen3ds2.Adyen3DS2Component.submitFingerprintAutomatically(Adyen3DS2Component.kt:272)
                                                                                                    	at com.adyen.checkout.adyen3ds2.Adyen3DS2Component.access$submitFingerprintAutomatically(Adyen3DS2Component.kt:59)
                                                                                                    	at com.adyen.checkout.adyen3ds2.Adyen3DS2Component$submitFingerprintAutomatically$1.invokeSuspend(Adyen3DS2Component.kt:0)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
                                                                                                    Caused by: com.adyen.threeds2.exception.InvalidInputException: Invalid challengeParameters.
                                                                                                    	at atd.a0.a.a(Unknown Source:2)
                                                                                                    	at com.adyen.threeds2.internal.i.a(Unknown Source:14)
                                                                                                    	at com.adyen.threeds2.internal.i.doChallenge(Unknown Source:11)
                                                                                                    	at com.adyen.checkout.adyen3ds2.Adyen3DS2Component.challengeShopper(Adyen3DS2Component.kt:296)
                                                                                                    	at com.adyen.checkout.adyen3ds2.Adyen3DS2Component.handleActionSubtype(Adyen3DS2Component.kt:144) 
                                                                                                    	at com.adyen.checkout.adyen3ds2.Adyen3DS2Component.handleActionInternal(Adyen3DS2Component.kt:136) 
                                                                                                    	at com.adyen.checkout.components.base.BaseActionComponent.handleAction(BaseActionComponent.java:56) 
                                                                                                    	at com.adyen.checkout.adyen3ds2.Adyen3DS2Component.submitFingerprintAutomatically(Adyen3DS2Component.kt:272) 
                                                                                                    	at com.adyen.checkout.adyen3ds2.Adyen3DS2Component.access$submitFingerprintAutomatically(Adyen3DS2Component.kt:59) 
                                                                                                    	at com.adyen.checkout.adyen3ds2.Adyen3DS2Component$submitFingerprintAutomatically$1.invokeSuspend(Adyen3DS2Component.kt:0) 
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) 
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) 
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584) 
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793) 
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697) 
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684) `

We are running R8 in fullmode as that is the new default. Disabling fullmode also seems to do the trick                   

@mikkoville Ya thanks! Wasn't aware of the bouncycastle library as we tried adding the the adyen libs in proguard rules to no avail but adding `android.enableR8.fullMode=false` in gradle.properties also seem to work.

**Comment by OscarSpruit** [comment] 2023-06-16 09:57
Thanks @mikkoville and @christianfindsen! The `adyen-android` SDK is using the `adyen-3ds2-android` SDK, so that explains why you both run into this issue. Together with the team that maintains the 3DS2 SDK we will look into a solution. I'll update this issue when we have something

**Comment by jonekdahl** [comment] 2023-08-22 08:42
It looks like [the underlying issue](https://github.com/Adyen/adyen-3ds2-android/issues/53) in `adyen-3ds2-android` was fixed a couple of weeks ago and included in version 2.2.14 of the library.

**Comment by jreij** [comment] 2023-08-30 09:52
Hi, we just released [4.13.0](https://github.com/Adyen/adyen-android/releases/tag/4.13.0) in which this issue should be fixed.

**Closed by jreij** 2023-08-30 09:52 UTC
Labels: Confirmed bug
