### ISSUE TITLE
getDate - value does not match expected pattern. 

### ISSUE THREAD

**Issue by dvasea1** [Adyen/adyen-android#110] opened 2019-09-23 14:31 UTC
Anyone can help me please? 
I got this error:
ExpiryDateInput: getDate - value does not match expected pattern.
    java.text.ParseException: Unparseable date: "0"

**Comment by ArmanSo** [comment] 2019-09-23 15:34
Hi @dvasea1 
as it said ExpiryDate is not valid.

Are you using drop-in or just card-component?
Can you give us more detail about your implementation?

Thanks.

**Comment by dvasea1** [comment] 2019-09-23 18:25
Yes, i'm using Drop in .

**Comment by caiofaustino** [comment] 2019-09-23 18:35
Hi @dvasea1, what value is on the date field when the issue happens? Can you give a few more detailed steps on how you reproduce the issue? Maybe a screenshot?

**Comment by dvasea1** [comment] 2019-09-23 19:07
![5155B977-ED28-4084-ADC1-1EDA6FD24CAA](https://user-images.githubusercontent.com/20457852/65454755-7e57a800-de4e-11e9-9e4f-5ab6aebfa36c.jpeg)

**Comment by dvasea1** [comment] 2019-09-23 19:08
This happens when the cursor is on Expiration input and this error os what i see on Logcat

**Comment by caiofaustino** [comment] 2019-09-24 07:31
What version are you on? This issue seems to be fixed in recent versions. Can you try updating?

**Comment by dvasea1** [comment] 2019-09-24 07:41
I'm using last version 3.4.0

**Comment by dvasea1** [comment] 2019-09-24 07:45
this is my method https://prnt.sc/pa5zug

**Comment by caiofaustino** [comment] 2019-09-24 07:49
That's weird, there is a try/catch block for that exception specifically. Can you please add this line of code before starting the payment and send me the logs right before the error happens?
`Logger.setLogcatLevel(Log.VERBOSE)`
Maybe a video or would also be helpful as we are not able to reproduce this here.

**Comment by dvasea1** [comment] 2019-09-24 08:02
https://prnt.sc/pa69li
Video can't upload .

**Comment by caiofaustino** [comment] 2019-09-24 08:21
That's really strange, from the the picture it looks like just a regular log, not something that would trigger an exception error. Maybe there is some other issue happening in the background.
Can you share what value are you using for your `pubKey`?

**Comment by dvasea1** [comment] 2019-09-24 08:28
pub.v2.8015603378460230.aHR0cHM6Ly9zdGFnZS5oYXN0bmV0LnNlLw._W06NPtLXobUKf9WloRnydl7iTBWfCtnKWWRnQqLrWk

**Comment by dvasea1** [comment] 2019-09-24 08:43
this pubKey is wrong?

**Comment by caiofaustino** [comment] 2019-09-24 08:46
Yes, the expected value starts with 5 numeric  digits and a | character.
`10001|ABC1234...`

**Comment by caiofaustino** [comment] 2019-09-25 13:11
Were you able to find the right public key? Let me know if you still have issues.

**Comment by caiofaustino** [comment] 2019-09-27 09:01
Since there was no reply I'll assume you fixd the issue and close the ticket. If it still happens please reopen it.

**Closed by caiofaustino** 2019-09-27 09:01 UTC
