### ISSUE TITLE
Issue with submitThreeDS2Fingerprint

### ISSUE THREAD

**Issue by NunoPalma** [Adyen/adyen-android#586] opened 2022-02-03 15:22 UTC
**Describe the bug**
This issue started occurring this morning, every request made to v1/submitThreeDS2Fingerprint contains the field fingerprintResult with over 6000 characters. According to https://docs.adyen.com/development-resources/error-codes#29_001-field-0-may-not-exceed-1-characters, something might have gone wrong in the generation process which caused the value to be too long. Since there were no client-side changes, was there any API changes done to the maximum amount of characters for that field?

Thanks in advance.

**Additional context**
* Using com.adyen.checkout:3ds2:4.4.0

```
D/CO.Adyen3DS2Component: identifyShopper - submitFingerprintAutomatically: true
D/CO.Adyen3DS2Component: initialize 3DS2 SDK
W/CO.Adyen3DS2Component: 3DS2 Service already initialized.
D/CO.Adyen3DS2Component: create transaction
D/CO.SubmitFingerprintRepository: Submitting fingerprint automatically
V/CO.SubmitFingerprintConnectionKt: call - https://checkoutshopper-test.adyen.com/checkoutshopper/v1/submitThreeDS2Fingerprint?token=test_<TOKEN>
E/CO.Adyen3DS2Component: Unexpected uncaught 3DS2 Exception
    java.io.IOException: {"status":422,"errorCode":"29_001","message":"Field 'fingerprintResult' may not exceed 3000 characters.","errorType":"validation"}
        at com.adyen.checkout.core.api.Connection.parseException(Connection.java:134)
        at com.adyen.checkout.core.api.Connection.handleResponse(Connection.java:175)
        at com.adyen.checkout.core.api.Connection.post(Connection.java:118)
        at com.adyen.checkout.adyen3ds2.connection.SubmitFingerprintConnection.call(SubmitFingerprintConnection.kt:37)
        at com.adyen.checkout.adyen3ds2.connection.SubmitFingerprintConnection.call(SubmitFingerprintConnection.kt:25)
        at com.adyen.checkout.adyen3ds2.repository.SubmitFingerprintRepository$submitFingerprint$$inlined$suspendedCall$1.invokeSuspend(ConnectionExt.kt:17)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by tw-manishp** [comment] 2022-02-04 07:45
We are also facing same issue. This issue started occurring since yesterday (3rd Feb, post afternoon). 
Did Adyen added some validation ?

**Comment by cernfr1993** [comment] 2022-02-04 08:40
We have the same problem. :/

**Comment by caiofaustino** [comment] 2022-02-04 09:37
Hi, thanks for reaching out, we believe to have found the cause of the issue in our TEST environment and will work to fix this asap.

**Comment by tw-manishp** [comment] 2022-02-04 09:48
> Hi, thanks for reaching out, we believe to have found the cause of the issue in our TEST environment and will work to fix this asap.

Thank you for the response, we are looking forward for it. Please get it fixed soon

**Comment by caiofaustino** [comment] 2022-02-06 09:19
The issue should be fixed by now, if any of you can confirm.

**Comment by NunoPalma** [comment] 2022-02-06 16:22
> The issue should be fixed by now, if any of you can confirm.

It is fixed. Thank you! @caiofaustino

**Comment by tw-manishp** [comment] 2022-02-07 07:31
> Reference in new

it is fixed 🎉 🎉 🎉 
Thank you @caiofaustino

**Comment by tw-manishp** [comment] 2022-02-07 07:31
> The issue should be fixed by now, if any of you can confirm.

it is fixed 🎉 🎉 🎉
Thank you @caiofaustino

**Closed** 2022-02-07 08:55 UTC
