### ISSUE TITLE
On error payment_failed background black with opacity dont dissmiss 

### ISSUE THREAD

**Issue by wilochoa** [Adyen/adyen-android#172] opened 2020-03-11 18:18 UTC
Hi, if i get an error, it show a dialog with the text of payment_failed.. i press ok, and the square with the message disappear, but keep an entire black opacity screen.. and the only way to make it disappear its touching back button.

**Comment by caiofaustino** [comment] 2020-03-24 09:52
Hi there,

Sorry for the delay, do you have more information on when this happens? Is it related to any specific device or Android version? Any specific payment method?

**Comment by caiofaustino** [comment] 2020-04-02 15:03
Closing this since there was no reply, feel free to reopen if you still have any problems.

**Comment by wilochoa** [comment] 2020-04-02 15:08
Sorry @caiofaustino, this still happen.  keep closed, but if you have any idea i will appreciate it. 

The issue happen always that i get and error in the payment proccess.. the library send a dialog showing the message of error. but when i touch okay, the dialog dissapear, but the screen keep a whole black transparency backgroud. 

i checked if that background were a part of my code, but no. 

it happen in all devices that i have.

**Comment by PhilippeBoisney** [comment] 2020-04-23 07:04
It happens also with the demo app: https://github.com/Adyen/adyen-android/tree/master/example-app. If the user has entered **a wrong card number**, the API returns an error but the user keeps stuck on this screen:

![Screenshot_1587625159](https://user-images.githubusercontent.com/6847959/80069114-19c60e00-8541-11ea-84f4-2b96e8372bc0.png)

It happens with the `ExampleSimplifiedDropInService` but works fine with the `ExampleDropInService`.

Can you take a lot at it @caiofaustino?

**Comment by PhilippeBoisney** [comment] 2020-04-23 07:35
Okay, after a few checks, it seems to work if you pass to true the `allow3DS2` in the `AdditionalData`.

Do you know why @caiofaustino ?

**Comment by caiofaustino** [comment] 2020-04-23 08:38
Hey @PhilippeBoisney,

I can't seem to reproduce this here. Can you check what the JSON response on the `ExampleSimplifiedDropInService.makeCall` returns? Maybe I can try to mock that here to see if there is some unexpected result.

Sorry @wilochoa I didn't see your reply earlier, do you still face this issue? Also something I'd like to see how you are implementing so that I can try to reproduce here.

**Comment by PhilippeBoisney** [comment] 2020-04-23 15:50
It seems to work now with the demo app, it was a bug on my side @caiofaustino

**Closed** 2020-04-23 19:35 UTC
